package dbmodel

type INTF_INT_EINVOICE_SETTING struct {
	EINVOICE_VERSION string
	CURRENCY_CODE string
	CURRENCY_EXCHANGE_RATE string
	BILLING_FREQUENCY string
	TAX_TYPE string
}

type INTF_INT_EINVOICE_EVENTS struct {
	EVENT_SEQ_NO string
	EINVOICE_TYPE_CODE string
	EINVOICE_CODE string
	EINVOICE_DATE string
	BILLING_DATE string
	PAYMENT_MODE string
	SUPPLIER_BANK_ACC string
	PAYMENT_TERMS string
	PRE_PAYMENT_AMT float64
	PRE_PAYMENT_DATE string
	PRE_PAYMENT_REF_NO string
	BILL_REF_NO string
	TOTAL_EXCLUDING_TAX float64
	TOTAL_INCLUDING_TAX float64
	TOTAL_PAYABLE_AMT float64
	TOTAL_NET_AMT float64
	TOTAL_TAX_AMT float64
	ROUNDING_AMT float64
	TOTAL_TAX_AMT_PER_TAX_TYPE float64
	TOTAL_TAXABLE_AMT_PER_TAX_TYPE float64
	TAX_EXEMPTION_DETAILS string
	TAX_EXEMPTION_AMT float64
}

type INTF_INT_EINVOICE_SUPPLIER struct {
	EVENT_SEQ_NO string
	SUPPLIER_NAME string
	SUPPLIER_TIN string
	SUPPLIER_REG_ID string
	SUPPLIER_SST_REG_NO string
	SUPPLIER_TOURISM_TAX_REG_NO string
	SUPPLIER_EMAIL string
	SUPPLIER_MSIC_CODE string
	SUPPLIER_BIZ_ACTY_DESC string
	ADDRESS_0 string
	ADDRESS_1 string
	ADDRESS_2 string
	ADDRESS_POSTAL string
	ADDRESS_CITY string
	ADDRESS_STATE string
	ADDRESS_COUNTRY string
	CONTACT_NO string
}

type INTF_INT_EINVOICE_BUYER struct {
	EVENT_SEQ_NO string
	BUYER_NAME string
	BUYER_TIN string
	BUYER_REG_ID string
	BUYER_SST_REG_NO string
	BUYER_EMAIL string
	ADDRESS_0 string
	ADDRESS_1 string
	ADDRESS_2 string
	ADDRESS_POSTAL string
	ADDRESS_CITY string
	ADDRESS_STATE string
	ADDRESS_COUNTRY string
	CONTACT_NO string
}

type INTF_INT_EINVOICE_LINE_ITEM struct {
	EVENT_SEQ_NO string
	CLASSIFICATION_CODE string
	ITEM_DESC string
	UNIT_PRICE float64
	TAX_TYPE string
	TAX_RATE float64
	TAX_AMT float64
	TAX_EXEMPTION_DESC string
	TAX_EXMEMPTED_AMT float64
	SUBTOTAL float64
	TOTAL_EXCLUDING_TAX float64
	QUANTITY float64
	MEASUREMENT string
	DISCOUNT_RATE float64
	DISCOUNT_AMT float64
	CHARGE_RATE float64
	CHARGE_AMT float64
}